spring:
  liquibase:
    enabled: 'true'
    change-log: db/master.yml
  docker:
    compose:
      file: src/main/docker/compose.yml
      lifecycle-management: none

  datasource:
    url: jdbc:mysql://localhost:3306/aftas
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
application:
  security:
    jwt:
      secret-key: 586B633834416E396D7436753879382F423F4428482B4C6250655367566B5970
      expiration: 1900000 #
      cookie-name: jwt-cookie
      refresh-token:
        expiration: 1296000000 # 15 days in ms
        cookie-name: refresh-jwt-cookie
