name: AFTAS_BACKEND
services:
  mysql:
    container_name: mysql_db
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=aftas'
      - 'MYSQL_ALLOW_EMPTY_PASSWORD=yes'
    ports:
      - '3306:3306'

  sonar:
    container_name: sonarqubee
    image: sonarqube:10.3.0-community
    environment:
      - SONAR_FORCEAUTHENTICATION=false
    ports:
      - 127.0.0.1:9001:9000
      - 127.0.0.1:9000:9000